version: "3.8"

services:
  mysql:
    image: mysql:5.7
    container_name: 9color_mysql_standalone
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root123456}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-6ui}
      MYSQL_USER: ${MYSQL_USER:-app}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-app123456}
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_backup:/var/backups
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./mysql/00-create-database.sql:/docker-entrypoint-initdb.d/00-create-database.sql
      - ./logs/mysql:/var/log/mysql
      - ./backup:/backup
    networks:
      - db-network
    restart: unless-stopped
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --bind-address=0.0.0.0
      --log-bin=mysql-bin
      --binlog-format=ROW
      --expire-logs-days=7
      --max-connections=300
      --innodb-buffer-pool-size=768M

  # 数据库备份服务
  mysql-backup:
    image: mysql:5.7
    container_name: 9color_mysql_backup
    depends_on:
      - mysql
    volumes:
      - mysql_backup:/var/backups
      - ./backup:/backup
      - ./scripts:/scripts
    networks:
      - db-network
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root123456}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-6ui}
    command: >
      sh -c "
        while ! mysqladmin ping -h mysql -u root -p${MYSQL_ROOT_PASSWORD:-root123456} --silent; do
          echo 'Waiting for MySQL to be ready...'
          sleep 10
        done
        echo 'MySQL is ready, starting backup scheduler...'
        /scripts/backup-scheduler.sh
      "
    restart: unless-stopped

  # phpMyAdmin 数据库管理面板
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2
    container_name: 9color_phpmyadmin
    ports:
      - "8090:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root123456}
      UPLOAD_LIMIT: 100M
      MEMORY_LIMIT: 512M
      MAX_EXECUTION_TIME: 300
    volumes:
      - ./phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
    depends_on:
      - mysql
    networks:
      - db-network
    restart: unless-stopped


volumes:
  mysql_data:
    driver: local
  mysql_backup:
    driver: local

networks:
  db-network:
    driver: bridge 